name: main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app_name:
          - ezadmis-deny-ns-deletion

    steps:

      - uses: actions/checkout@v3

      - name: dockerhub meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: guoyk/${{matrix.app_name}}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}

      - name: dockerhub login
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          username: guoyk
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: dockerhub build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: ./Dockerfile
          build-args: "APP_NAME=${{matrix.app_name}}"
